server:
  port: 9001
  servlet:
    context-path: /resource-server

security:
  oauth2:
#    client:
#      clientId: myresource
#      clientSecret: myresourcesecret
    resource:
      user-info-uri: http://localhost:9002/auth-server/user