server:
  port: 9001
  context-path: /resource-server

security:
  oauth2:
    client:
      clientId: myclient
      clientSecret: myclientsecret
    resource:
      user-info-uri: http://localhost:9002/auth-server/user
 